import { z } from 'zod';

export const createLeadSchema = z.object({
    body: z.object({
        name: z.string().min(1, 'Name is required'),
        phone: z.string().optional(),
        interestedProduct: z.string().optional(),
        status: z.enum(['new', 'contacted', 'interested', 'converted', 'lost']).optional(),
        nextFollowUpDate: z.string().datetime().optional().or(z.string().optional()),
        notes: z.string().optional(),
        
        // Optional Policy/Quote Draft Fields
        policyType: z.enum(['motor', 'health', 'life', 'non_motor', 'other']).optional(),
        companyId: z.string().optional().or(z.literal('')),
        vehicleNumber: z.string().optional().or(z.literal('')),
        make: z.string().optional().or(z.literal('')),
        model: z.string().optional().or(z.literal('')),
        registrationDate: z.string().optional().nullable(),
        vehicleClass: z.enum(['TW', 'PCV', 'PVT', 'GCV', 'Misc_D', 'CPM', 'Fire', 'Public_Liability', 'SAOD_TW', 'SAOD_PVT', 'CPA', 'Home_Insurance', 'RAK_Policy', 'Others']).optional(),
        idv: z.number().min(0).optional(),
        od: z.number().min(0).optional(),
        tp: z.number().min(0).optional(),
        tax: z.number().min(0).optional(),
        totalPremium: z.number().min(0).optional(),
        premiumAmount: z.number().min(0).optional(),
        startDate: z.string().optional(),
        expiryDate: z.string().optional(),
        dealerId: z.string().optional().or(z.literal('')),
        policyOrigin: z.enum(['new_vehicle', 'fresh', 'external_renewal', 'in_system_renewal']).optional(),
        ncbPercentage: z.number().min(0).max(50).optional().nullable(),
        tpStartDate: z.string().optional().nullable(),
        tpEndDate: z.string().optional().nullable(),
    }),
});

export const updateLeadSchema = z.object({
    body: z.object({
        name: z.string().min(1).optional(),
        phone: z.string().optional(),
        interestedProduct: z.string().optional(),
        status: z.enum(['new', 'contacted', 'interested', 'converted', 'lost']).optional(),
        nextFollowUpDate: z.string().optional().nullable(),
        notes: z.string().optional().nullable(),

        // Optional Policy/Quote Draft Fields
        policyType: z.enum(['motor', 'health', 'life', 'non_motor', 'other']).optional(),
        companyId: z.string().optional().or(z.literal('')),
        vehicleNumber: z.string().optional().or(z.literal('')),
        make: z.string().optional().or(z.literal('')),
        model: z.string().optional().or(z.literal('')),
        registrationDate: z.string().optional().nullable(),
        vehicleClass: z.enum(['TW', 'PCV', 'PVT', 'GCV', 'Misc_D', 'CPM', 'Fire', 'Public_Liability', 'SAOD_TW', 'SAOD_PVT', 'CPA', 'Home_Insurance', 'RAK_Policy', 'Others']).optional(),
        idv: z.number().min(0).optional(),
        od: z.number().min(0).optional(),
        tp: z.number().min(0).optional(),
        tax: z.number().min(0).optional(),
        totalPremium: z.number().min(0).optional(),
        premiumAmount: z.number().min(0).optional(),
        startDate: z.string().optional(),
        expiryDate: z.string().optional(),
        dealerId: z.string().optional().or(z.literal('')),
        policyOrigin: z.enum(['new_vehicle', 'fresh', 'external_renewal', 'in_system_renewal']).optional(),
        ncbPercentage: z.number().min(0).max(50).optional().nullable(),
        tpStartDate: z.string().optional().nullable(),
        tpEndDate: z.string().optional().nullable(),
    }),
    params: z.object({
        id: z.string().uuid(),
    }),
});

export const convertLeadSchema = z.object({
    params: z.object({
        id: z.string().uuid(),
    }),
    body: z.object({
        address: z.string().optional(),
        email: z.string().email().optional().or(z.literal('')),
        policyOrigin: z.enum(['new_vehicle', 'fresh', 'external_renewal', 'in_system_renewal']).optional(),
        ncbPercentage: z.number().min(0).max(50).optional().nullable(),
        policyNumber: z.string().optional(),
        policyType: z.enum(['motor', 'life', 'health', 'non_motor', 'other']).optional(),
        companyId: z.string().uuid().optional(),
        premiumAmount: z.number().min(0).optional(),
        startDate: z.string().optional(),
        expiryDate: z.string().optional(),
        vehicleNumber: z.string().optional().nullable(),
        make: z.string().optional().nullable(),
        model: z.string().optional().nullable(),
        registrationDate: z.string().optional().nullable(),
        vehicleClass: z.enum(['TW', 'PCV', 'PVT', 'GCV', 'Misc_D', 'CPM', 'Fire', 'Public_Liability', 'SAOD_TW', 'SAOD_PVT', 'CPA', 'Home_Insurance', 'RAK_Policy', 'Others']).optional().nullable(),
        idv: z.number().min(0).optional().nullable(),
        od: z.number().min(0).optional().nullable(),
        tp: z.number().min(0).optional().nullable(),
        tax: z.number().min(0).optional().nullable(),
        totalPremium: z.number().min(0).optional().nullable(),
        dealerId: z.string().optional().nullable(),
        tpStartDate: z.string().optional().nullable(),
        tpEndDate: z.string().optional().nullable(),
    }),
});
